"""006/unique uid

Revision ID: 35af944ce3dd
Revises: 5f773c2e7b46
Create Date: 2021-12-27 15:05:57.076839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35af944ce3dd'
down_revision = '5f773c2e7b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['firebase_id'])
    op.drop_column('users', 'verified')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
