"""adding game field as varchar255

Revision ID: 7be264663c29
Revises: 82c1df0542a7
Create Date: 2022-03-15 04:58:57.525235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be264663c29'
down_revision = '82c1df0542a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('game', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'game')
    # ### end Alembic commands ###
