"""fix bracket_id for user_tournament

Revision ID: 82c1df0542a7
Revises: 9bea906e3151
Create Date: 2022-01-11 08:40:00.119979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c1df0542a7'
down_revision = '9bea906e3151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_tournaments_bracket_id_fkey', 'user_tournaments', type_='foreignkey')
    op.create_foreign_key(None, 'user_tournaments', 'brackets', ['bracket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tournaments', type_='foreignkey')
    op.create_foreign_key('user_tournaments_bracket_id_fkey', 'user_tournaments', 'tournaments', ['bracket_id'], ['id'])
    # ### end Alembic commands ###
