"""add tournament description, start, end date


Revision ID: 9b2bc7ef5675
Revises: 82c1df0542a7
Create Date: 2022-01-28 18:03:45.732488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2bc7ef5675'
down_revision = '82c1df0542a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brackets', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tournaments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tournaments', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tournaments', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tournaments', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tournaments', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'ended_at')
    op.drop_column('tournaments', 'started_at')
    op.drop_column('tournaments', 'end_date')
    op.drop_column('tournaments', 'start_date')
    op.drop_column('tournaments', 'description')
    op.drop_column('brackets', 'description')
    # ### end Alembic commands ###
