"""add bracket_id to user_tournament

Revision ID: 9bea906e3151
Revises: 35af944ce3dd
Create Date: 2022-01-11 08:19:06.841717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bea906e3151'
down_revision = '35af944ce3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tournaments', sa.Column('bracket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_tournaments', 'tournaments', ['bracket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tournaments', type_='foreignkey')
    op.drop_column('user_tournaments', 'bracket_id')
    # ### end Alembic commands ###
